# Generated by Django 3.2.8 on 2022-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=10)),
                ('word', models.CharField(max_length=25)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
