# Generated by Django 3.2.8 on 2022-04-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BoneBroth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=25)),
                ('word', models.CharField(max_length=25)),
                ('count', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bs4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=25)),
                ('word', models.CharField(max_length=25)),
                ('count', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='org',
            field=models.CharField(max_length=25),
        ),
    ]
