# Generated by Django 3.2.8 on 2022-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220409_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtvArchive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=25)),
                ('date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopWords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
