# Generated by Django 3.2.8 on 2022-04-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_ctvarchive_topwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctvarchive',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
