# Generated by Django 3.2.8 on 2022-04-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_bonebrotharchive_deeparchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonebrotharchive',
            name='org',
            field=models.CharField(default='ctv', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deeparchive',
            name='org',
            field=models.CharField(default='ctv', max_length=25),
            preserve_default=False,
        ),
    ]
