# Generated by Django 3.2.13 on 2022-04-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220413_0344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoneBroth',
        ),
        migrations.DeleteModel(
            name='Bs4',
        ),
        migrations.DeleteModel(
            name='CtvArchive',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
