# Generated by Django 3.2 on 2022-05-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_millions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWordsByOrg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=25)),
                ('org', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
