# Generated by Django 4.0.5 on 2022-11-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
